import Navbar from '@components/Navbar'
import Head from 'next/head'
import Footer from '@components/Footer'
import TopTracks from '@components/TopTracks'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <TopTracks />
      <Footer />
    </>
  )
}
