import Navbar from '@components/Navbar'
import Head from 'next/head'
import Footer from '@components/Footer'
import HeroSection from '@components/HeroSection'
import { fetcher } from 'pages/api/fetcher'
import LoadSection from '@components/Loading'
import useSWR from 'swr'

const apiUrl = '/api/now_playing'

export default function Home() {
  const { data, error } = useSWR(apiUrl, fetcher)

  if (error) return <p>error</p>
  if (!data) return <LoadSection />
  return (
    <>
      <Head>
        <title>Music</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <HeroSection />
      <Footer
        songUrl={data?.songUrl}
        title={data?.title}
        artist={data?.artist}
      />
    </>
  )
}
